- app.js
- routes/register.js
- templates/home.html
Pulled out the register routing into its own file, will help with future merges and cleaning up the app.js file.
> added registerRoute

- templates/register.html
centered the register text and form.
> Alisonbranch

- app.js
- models/workout.js
- routes/login.js
- routes/register.js
- seeders/20201015134609-demo-user.js
- templates/home.html
- templates/login.html
- templates/partials/head.html
- templates/register.html
Added a bootstrap form into the login page. Fixed an issue with the workout-model file... previously I had on the workouts that it hasOne(models.User)...but I should have had BelongsTo(models.User). Also added a loginRoute, just did the same thing we had done for the registerRoute, but for the login route.
> bootstrapLogin created loginRoute.js

- public/styles.css
- templates/dashboard.html
- templates/register.html
> made register.html a little pretty

- app.js
- public/styles.css
- public/workouts/workouts_script.js
- routes/dashboard.js
- templates/dashboard.html
- templates/home.html
- templates/partials/head.html
- templates/register.html
added calendar feature, made sure the nav bar would go to the right pages.
> added calendar and fixed nav bar

- app.js
- public/workouts/workouts_script.js
- routes/dashboard.js
- routes/workouts.js
- templates/dashboard.html
added api call and route for return workouts in the last 2 weeks
> api call to return workouts

- public/workouts/workouts_script.js
- routes/dashboard.js
- routes/workouts.js
- templates/dashboard.html
Fixed the form on the dashboard page, unfortunately had to go back to the previous form where it is underneath the calendar. Got the API call to return a list of all the workouts that are for the current logged in user and were done within the last two weeks.
> Plooney81 workouts api call

- public/workouts/workouts_script.js
- routes/dashboard.js
- routes/workouts.js
ability to get different type of workouts from the get call to the workouts API route.
> added a type call for front and backend workouts api

- public/workouts/workouts_script.js
- routes/register.js
- routes/workouts.js
- templates/dashboard.html
Error handling and Functionality for the pr lists, API call that returns and puts list items on the page for each users workout.
> added workouts to the PR list

- migrations/20201016160754-create-challenge.js
- models/challenge.js
- models/user.js
- public/challenges/challenges_script.js
- routes/challenges.js
- templates/challenge.html
Added challenges template and route, began on new migrations
> before migration fixes, added challenges template and routes

- app.js
- models/challenge.js
- models/user.js
- models/workout.js
- routes/challenges.js
Just need to fix the relation of user_challenges, other than that we are almost there
> close to fixing the relation between users and challenges

- public/styles.css
- templates/challenge.html
- templates/dashboard.html
- templates/login.html
- templates/partials/footer.html
- templates/partials/head.html
- templates/register.html
made sure that damn profile page was all centered 🤬
> css changes

- app.js
- migrations/20201016160754-create-challenge.js
- migrations/20201016201045-join-user-to-challenges.js
- models/challenge.js
- public/challenges/challenges_script.js
- routes/challenges.js
- routes/challenges_api.js
- routes/workouts.js
- templates/challenge.html
Added API route for getting a users challenges, also added a basic front end call to that route to test.
> Plooney81 challenges api routing

- public/challenges/challenges_script.js
- public/workouts/workouts_script.js
- routes/challenges_api.js
- routes/workouts.js
Made a few changes to the API calls that accept a workoutType of all in the query. If the workoutType of all is passed in the Get Request, then it will return all of the workouts/challenges types from the DB, i.e. both cycling and running.
> Plooney81 calendar changes

- public/styles.css
- public/workouts/workouts_script.js
- routes/dashboard.js
- routes/workouts.js
- templates/challenge.html
adjusted calendar, set up time zone, fixed rendering of data for PR's
> adjust calendar

- README.md
- app.js
- public/styles.css
- public/workouts/workouts_script.js
- routes/challenges.js
- routes/challenges_api.js
- routes/checkAuth.js
- routes/dashboard.js
- routes/login.js
- routes/workouts.js
These fix the calendar issues we were having earlier, the fixes are 48 through 50 in the workouts_script.js. They were not popping up in the calendar because the dates that were only one digit in the calendar were being returned as 01 or 02 from the API call, and were not matching to the correct date in the front end calendar (because those dates are 1 or 2). To fix it, in workouts_script.js I simply added an if statement checking if the first index of the date var was 0...if it was then the date var is reassigned to the second index i.e. the actual number...this fixed it.
> Plooney81 more calendar work

- public/styles.css
- templates/challenge.html
added to form, public/private option, title option, description option and changed the wording a bit to make it more user friendly. Also made sure they all fit within the same div and put a border around it.
> added to form for challenges

- public/challenges/challenges_script.js
- routes/challenges_api.js
- seeders/20201020152748-demo-workouts.js
- seeders/20201020152800-demo-challenges.js
- seeders/20201020153012-demo-userChallenges.js
- templates/dashboard.html
Base routes for challenges apis
> More challenges work

- public/styles.css
- templates/challenge.html
added more form info on challenge.html.
> more on challenge.html

- app.js
- public/challenges/challenges_script.js
- routes/challenges_api.js
- routes/login.js
- seeders/20201020152800-demo-challenges.js
Fixed clicking anywhere on the page bug, as well as the where statement for finding the user bug...issue with the object we were feeding into the db.User.findOne, so I put the where statement back into the method call instead of taking it out as a separate object.
> minor challenge page bug fixes

- app.js
- templates/challenge.html
> changed challenge page ccs, centering
